// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSRbGRhZ_jtJKVZpR1IyXvj9mRXHWFClo',
    appId: '1:270789494028:web:694d97369ee21281e7f529',
    messagingSenderId: '270789494028',
    projectId: 'health-app-6a717',
    authDomain: 'health-app-6a717.firebaseapp.com',
    storageBucket: 'health-app-6a717.appspot.com',
    measurementId: 'G-GF68YYGDN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpfuZbok1EPI2OuozwX2O_x8izZO56exo',
    appId: '1:270789494028:android:bb13412c7df79143e7f529',
    messagingSenderId: '270789494028',
    projectId: 'health-app-6a717',
    storageBucket: 'health-app-6a717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj9CKPHm6hlANM_K2WQwqoSNH3GaBvUFk',
    appId: '1:270789494028:ios:3a18e804bb1a58fbe7f529',
    messagingSenderId: '270789494028',
    projectId: 'health-app-6a717',
    storageBucket: 'health-app-6a717.appspot.com',
    iosBundleId: 'com.example.flutterDietApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj9CKPHm6hlANM_K2WQwqoSNH3GaBvUFk',
    appId: '1:270789494028:ios:3a18e804bb1a58fbe7f529',
    messagingSenderId: '270789494028',
    projectId: 'health-app-6a717',
    storageBucket: 'health-app-6a717.appspot.com',
    iosBundleId: 'com.example.flutterDietApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSRbGRhZ_jtJKVZpR1IyXvj9mRXHWFClo',
    appId: '1:270789494028:web:5b73a214da2aa03ee7f529',
    messagingSenderId: '270789494028',
    projectId: 'health-app-6a717',
    authDomain: 'health-app-6a717.firebaseapp.com',
    storageBucket: 'health-app-6a717.appspot.com',
    measurementId: 'G-W38QEFKH5Y',
  );
}
